export type Brand = {
  id: string;
  name: string;
  icon: string;
};

export type PhoneModel = {
  id: string;
  brandId: string;
  name: string;
  image?: string;
};

export type PartCategory = 'SCREENS' | 'Batteries' | 'Back Glass' | 'Charging Flexes' | 'ICs' | 'Tools' | 'Screen Protectors';

export type InventoryItem = {
  id: string;
  modelId: string;
  brandId?: string;
  category: PartCategory;
  name: string;
  stock: number;
  retailPrice: number;
  wholesaleCost: number;
  barcode?: string;
  compatibilityNote?: string;
};

export const BRANDS: Brand[] = [
  { id: 'apple', name: 'Apple', icon: 'apple' },
  { id: 'samsung', name: 'Samsung', icon: 'smartphone' },
  { id: 'infinix', name: 'Infinix', icon: 'cpu' },
  { id: 'techno', name: 'Tecno', icon: 'smartphone' },
  { id: 'itel', name: 'Itel', icon: 'smartphone' },
  { id: 'oppo', name: 'Oppo', icon: 'camera' },
  { id: 'realme', name: 'Realme', icon: 'zap' },
  { id: 'xiaomi', name: 'Xiaomi', icon: 'smartphone' },
  { id: 'ace-buzz', name: 'Ace Buzz', icon: 'box' },
  { id: 'condor', name: 'Condor', icon: 'smartphone' },
  { id: 'huawei', name: 'Huawei', icon: 'wifi' },
  { id: 'honor', name: 'Honor', icon: 'smartphone' },
  { id: 'vivo', name: 'Vivo', icon: 'smartphone' },
  { id: 'oneplus', name: 'OnePlus', icon: 'zap' },
  { id: 'nokia', name: 'Nokia', icon: 'smartphone' },
  { id: 'google', name: 'Google Pixel', icon: 'search' },
  { id: 'lenovo', name: 'Lenovo', icon: 'tablet' },
];

export const MOCK_MODELS: PhoneModel[] = [
  // APPLE
  { id: 'iph-6', brandId: 'apple', name: 'iPhone 6 / 6S' },
  { id: 'iph-6-plus', brandId: 'apple', name: 'iPhone 6+ / 6S+' },
  { id: 'iph-7', brandId: 'apple', name: 'iPhone 7' },
  { id: 'iph-7-plus', brandId: 'apple', name: 'iPhone 7+' },
  { id: 'iph-8', brandId: 'apple', name: 'iPhone 8' },
  { id: 'iph-x', brandId: 'apple', name: 'iPhone X' },
  { id: 'iph-xr', brandId: 'apple', name: 'iPhone XR' },
  { id: 'iph-xs', brandId: 'apple', name: 'iPhone XS' },
  { id: 'iph-xs-max', brandId: 'apple', name: 'iPhone XS Max' },
  { id: 'iph-11', brandId: 'apple', name: 'iPhone 11' },
  { id: 'iph-11-pro', brandId: 'apple', name: 'iPhone 11 Pro' },
  { id: 'iph-11-pro-max', brandId: 'apple', name: 'iPhone 11 Pro Max' },
  { id: 'iph-12', brandId: 'apple', name: 'iPhone 12 / 12 Pro' },
  { id: 'iph-12-mini', brandId: 'apple', name: 'iPhone 12 Mini' },
  { id: 'iph-12-pro-max', brandId: 'apple', name: 'iPhone 12 Pro Max' },
  { id: 'iph-13', brandId: 'apple', name: 'iPhone 13' },
  { id: 'iph-13-pro', brandId: 'apple', name: 'iPhone 13 Pro' },
  { id: 'iph-13-pro-max', brandId: 'apple', name: 'iPhone 13 Pro Max' },
  { id: 'iph-14', brandId: 'apple', name: 'iPhone 14' },
  { id: 'iph-14-pro', brandId: 'apple', name: 'iPhone 14 Pro' },
  { id: 'iph-14-pro-max', brandId: 'apple', name: 'iPhone 14 Pro Max' },
  { id: 'iph-15', brandId: 'apple', name: 'iPhone 15' },
  { id: 'iph-15-pro', brandId: 'apple', name: 'iPhone 15 Pro' },
  { id: 'iph-15-pro-max', brandId: 'apple', name: 'iPhone 15 Pro Max' },
  { id: 'iph-16', brandId: 'apple', name: 'iPhone 16' },
  { id: 'iph-16-pro-max', brandId: 'apple', name: 'iPhone 16 Pro Max' },
  { id: 'iph-17', brandId: 'apple', name: 'iPhone 17' },
  { id: 'iph-17-pro', brandId: 'apple', name: 'iPhone 17 Pro' },
  { id: 'iph-17-pro-max', brandId: 'apple', name: 'iPhone 17 Pro Max' },

  // SAMSUNG
  { id: 'sam-a01', brandId: 'samsung', name: 'Galaxy A01 / A01 Core' },
  { id: 'sam-a02s-a03s', brandId: 'samsung', name: 'Galaxy A02S / A03S' },
  { id: 'sam-a03-core', brandId: 'samsung', name: 'Galaxy A03 Core' },
  { id: 'sam-a04', brandId: 'samsung', name: 'Galaxy A04 / A04S / A04E' },
  { id: 'sam-a05', brandId: 'samsung', name: 'Galaxy A05 / A05S' },
  { id: 'sam-a06', brandId: 'samsung', name: 'Galaxy A06' },
  { id: 'sam-a07', brandId: 'samsung', name: 'Galaxy A07' },
  { id: 'sam-a10-a10s', brandId: 'samsung', name: 'Galaxy A10 / A10S' },
  { id: 'sam-a11-m11', brandId: 'samsung', name: 'Galaxy A11 / M11' },
  { id: 'sam-a12-m12', brandId: 'samsung', name: 'Galaxy A12 / M12 / A022' },
  { id: 'sam-a13', brandId: 'samsung', name: 'Galaxy A13' },
  { id: 'sam-a14', brandId: 'samsung', name: 'Galaxy A14 4G/5G' },
  { id: 'sam-a15', brandId: 'samsung', name: 'Galaxy A15' },
  { id: 'sam-a16', brandId: 'samsung', name: 'Galaxy A16 / M16' },
  { id: 'sam-a17', brandId: 'samsung', name: 'Galaxy A17' },
  { id: 'sam-a20-a20s', brandId: 'samsung', name: 'Galaxy A20 / A20S' },
  { id: 'sam-a21s', brandId: 'samsung', name: 'Galaxy A21S' },
  { id: 'sam-a22', brandId: 'samsung', name: 'Galaxy A22 / M22' },
  { id: 'sam-a23', brandId: 'samsung', name: 'Galaxy A23 4G/5G' },
  { id: 'sam-a24', brandId: 'samsung', name: 'Galaxy A24' },
  { id: 'sam-a25', brandId: 'samsung', name: 'Galaxy A25' },
  { id: 'sam-a26', brandId: 'samsung', name: 'Galaxy A26' },
  { id: 'sam-a30-a50', brandId: 'samsung', name: 'Galaxy A30 / A30S / A50' },
  { id: 'sam-a31', brandId: 'samsung', name: 'Galaxy A31' },
  { id: 'sam-a32', brandId: 'samsung', name: 'Galaxy A32 4G/5G' },
  { id: 'sam-a33', brandId: 'samsung', name: 'Galaxy A33 5G' },
  { id: 'sam-a34', brandId: 'samsung', name: 'Galaxy A34 / F54' },
  { id: 'sam-a35', brandId: 'samsung', name: 'Galaxy A35 5G' },
  { id: 'sam-a36', brandId: 'samsung', name: 'Galaxy A36 5G' },
  { id: 'sam-a51', brandId: 'samsung', name: 'Galaxy A51' },
  { id: 'sam-a52', brandId: 'samsung', name: 'Galaxy A52' },
  { id: 'sam-a53', brandId: 'samsung', name: 'Galaxy A53 5G' },
  { id: 'sam-a54', brandId: 'samsung', name: 'Galaxy A54 5G' },
  { id: 'sam-a55', brandId: 'samsung', name: 'Galaxy A55 5G' },
  { id: 'sam-a56', brandId: 'samsung', name: 'Galaxy A56 5G' },
  { id: 'sam-a70-a71-a72-a73', brandId: 'samsung', name: 'Galaxy A70 / A71 / A72 / A73' },
  { id: 'sam-j-series', brandId: 'samsung', name: 'Galaxy J Series (J4/J5/J6/J7/J8)' },
  { id: 'sam-m-series', brandId: 'samsung', name: 'Galaxy M Series (M15/M23/M30/M33/M51/M55)' },
  { id: 'sam-note-series', brandId: 'samsung', name: 'Galaxy Note Series (8/9/10/20/Ultra)' },
  { id: 'sam-s10', brandId: 'samsung', name: 'Galaxy S10 / S10+ / S10E' },
  { id: 'sam-s20', brandId: 'samsung', name: 'Galaxy S20 / FE / Plus / Ultra' },
  { id: 'sam-s21', brandId: 'samsung', name: 'Galaxy S21 / FE / Plus / Ultra' },
  { id: 'sam-s22', brandId: 'samsung', name: 'Galaxy S22 / Plus / Ultra' },
  { id: 'sam-s23', brandId: 'samsung', name: 'Galaxy S23 / FE / Plus / Ultra' },
  { id: 'sam-s24', brandId: 'samsung', name: 'Galaxy S24 / FE / Plus / Ultra' },
  { id: 'sam-s25', brandId: 'samsung', name: 'Galaxy S25 / Plus / Ultra' },
  { id: 'sam-tab-series', brandId: 'samsung', name: 'Galaxy Tab Series (A7/T500/T285/T590)' },
  { id: 'sam-z-flip6', brandId: 'samsung', name: 'Galaxy Z Flip 6' },

  // INFINIX
  { id: 'inf-hot-series', brandId: 'infinix', name: 'Infinix Hot Series (8/9/10/11/12/20/30/40/50)' },
  { id: 'inf-note-series', brandId: 'infinix', name: 'Infinix Note Series (7/8/11/12/20/30/40)' },
  { id: 'inf-smart-series', brandId: 'infinix', name: 'Infinix Smart Series (3/4/5/6/7/8/9/10)' },

  // TECNO & ITEL
  { id: 'tecno-camon-spark', brandId: 'techno', name: 'Tecno Camon & Spark Series' },
  { id: 'itel-a-series', brandId: 'itel', name: 'Itel A-Series & S23 / P36 / P37' },

  // OPPO & REALME
  { id: 'oppo-a-series', brandId: 'oppo', name: 'Oppo A-Series (A15/A16/A53/A54/A74/A94)' },
  { id: 'oppo-reno-series', brandId: 'oppo', name: 'Oppo Reno Series (2/3/4/5/6/7/8/9/10/12F/13F)' },
  { id: 'realme-c-series', brandId: 'realme', name: 'Realme C-Series (C11/C21/C30/C33/C53/C55/C61/C63)' },
  { id: 'realme-gt-series', brandId: 'realme', name: 'Realme GT & Number Series (10/11/12/13/GT Neo)' },

  // XIAOMI & POCO & REDMI
  { id: 'xiaomi-mi-series', brandId: 'xiaomi', name: 'Xiaomi Mi Flagship (8/9/10/11/13/14 Ultra)' },
  { id: 'xiaomi-redmi-numbered', brandId: 'xiaomi', name: 'Redmi Standard (7/8/9/10/12/13/14/15/A1/A2/A3)' },
  { id: 'xiaomi-redmi-note', brandId: 'xiaomi', name: 'Redmi Note Series (7/8/9/10/11/12/13/14)' },
  { id: 'xiaomi-poco-series', brandId: 'xiaomi', name: 'Poco Series (M3/F3/F5/X3/X4/X5/X6)' },

  // ACE BUZZ & CONDOR
  { id: 'ace-buzz-models', brandId: 'ace-buzz', name: 'Ace Buzz (2/3/4/5/6/7 Lite/Prime/Pro)' },
  { id: 'condor-models', brandId: 'condor', name: 'Condor (L1+/L5/L8/Nova 60/70/P6)' },

  // HUAWEI & HONOR
  { id: 'huw-p-mate-series', brandId: 'huawei', name: 'Huawei P & Mate Series (P10/P20/P30/Mate 30/40/60/Pura 70)' },
  { id: 'huw-y-nova-series', brandId: 'huawei', name: 'Huawei Y & Nova Series (Y6/Y7/Nova 9/Nova 5T)' },
  { id: 'honor-series', brandId: 'honor', name: 'Honor Series (8/9/10/50/80/90/200/X7/X8/X9)' },

  // VIVO, ONEPLUS, NOKIA, GOOGLE PIXEL, LENOVO
  { id: 'vivo-models', brandId: 'vivo', name: 'Vivo Y-Series (Y02/Y03/Y18/Y20/Y21/Y33/Y36)' },
  { id: 'oneplus-models', brandId: 'oneplus', name: 'OnePlus (3/5/6/7/8/9RT/Nord/12R)' },
  { id: 'nokia-models', brandId: 'nokia', name: 'Nokia (2.2/2.3/2.4/3.4/5/6/C1/C3)' },
  { id: 'google-pixel-models', brandId: 'google', name: 'Google Pixel (3A/5A/6/7/8/9 Pro/XL)' },
  { id: 'lenovo-tab-models', brandId: 'lenovo', name: 'Lenovo Tabs (M8/X606/M10+)' },
];

export const PART_CATEGORIES: PartCategory[] = [
  'SCREENS', 'Batteries', 'Back Glass', 'Charging Flexes', 'ICs', 'Tools', 'Screen Protectors'
];

export const INITIAL_GLOBAL_INVENTORY: InventoryItem[] = [
  // --- APPLE ---
  { id: 'IPH-11-STD', modelId: 'iph-11', category: 'SCREENS', name: 'LCD IPH 11', stock: 0, retailPrice: 2200, wholesaleCost: 1870 },
  { id: 'IPH-11-IFIX', modelId: 'iph-11', category: 'SCREENS', name: 'LCD IPH 11 IFIX', stock: 0, retailPrice: 3800, wholesaleCost: 3230, compatibilityNote: 'iFix Premium' },
  { id: 'IPH-11P-STD', modelId: 'iph-11-pro', category: 'SCREENS', name: 'LCD IPH 11 PRO', stock: 0, retailPrice: 2550, wholesaleCost: 2167 },
  { id: 'IPH-11P-GX-INCEL', modelId: 'iph-11-pro', category: 'SCREENS', name: 'LCD IPH 11 PRO GX INCEL', stock: 0, retailPrice: 2600, wholesaleCost: 2210 },
  { id: 'IPH-11P-GX-OR', modelId: 'iph-11-pro', category: 'SCREENS', name: 'LCD IPH 11 PRO GX OR', stock: 0, retailPrice: 4950, wholesaleCost: 4200, compatibilityNote: 'Original GX' },
  { id: 'IPH-11PM-STD', modelId: 'iph-11-pro-max', category: 'SCREENS', name: 'LCD IPH 11 PRO MAX', stock: 0, retailPrice: 2600, wholesaleCost: 2210 },
  { id: 'IPH-11PM-GX-INCEL', modelId: 'iph-11-pro-max', category: 'SCREENS', name: 'LCD IPH 11 PRO MAX GX INCEL', stock: 0, retailPrice: 2600, wholesaleCost: 2210 },
  { id: 'IPH-11PM-GX-OR', modelId: 'iph-11-pro-max', category: 'SCREENS', name: 'LCD IPH 11 PRO MAX GX OR', stock: 0, retailPrice: 6650, wholesaleCost: 5650 },
  { id: 'IPH-11PM-OLED-IFIX', modelId: 'iph-11-pro-max', category: 'SCREENS', name: 'LCD IPH 11 PRO MAX OLED IFIX', stock: 0, retailPrice: 6600, wholesaleCost: 5610 },
  { id: 'IPH-11P-OLED-IFIX', modelId: 'iph-11-pro', category: 'SCREENS', name: 'LCD IPH 11 PRO OLED IFIX', stock: 0, retailPrice: 4900, wholesaleCost: 4165 },
  { id: 'IPH-12-STD', modelId: 'iph-12', category: 'SCREENS', name: 'LCD IPH 12 / 12 PRO', stock: 0, retailPrice: 2600, wholesaleCost: 2210, compatibilityNote: 'Fits 12 & 12 Pro' },
  { id: 'IPH-12-GX-INCEL', modelId: 'iph-12', category: 'SCREENS', name: 'LCD IPH 12 / 12 PRO GX INCEL', stock: 0, retailPrice: 2700, wholesaleCost: 2295 },
  { id: 'IPH-12-GX-OR', modelId: 'iph-12', category: 'SCREENS', name: 'LCD IPH 12 / 12 PRO GX OR', stock: 0, retailPrice: 6300, wholesaleCost: 5355 },
  { id: 'IPH-12-IFIX', modelId: 'iph-12', category: 'SCREENS', name: 'LCD IPH 12 / 12 PRO IFIX', stock: 0, retailPrice: 3950, wholesaleCost: 3350 },
  { id: 'IPH-12-OLED-IFIX', modelId: 'iph-12', category: 'SCREENS', name: 'LCD IPH 12 / 12 PRO OLED IFIX', stock: 0, retailPrice: 6300, wholesaleCost: 5355 },
  { id: 'IPH-12M-GX-OR', modelId: 'iph-12-mini', category: 'SCREENS', name: 'LCD IPH 12 MINI GX OR', stock: 0, retailPrice: 8500, wholesaleCost: 7225 },
  { id: 'IPH-12M-IFIX', modelId: 'iph-12-mini', category: 'SCREENS', name: 'LCD IPH 12 MINI IFIX', stock: 0, retailPrice: 5000, wholesaleCost: 4250 },
  { id: 'IPH-12PM-STD', modelId: 'iph-12-pro-max', category: 'SCREENS', name: 'LCD IPH 12 PRO MAX', stock: 0, retailPrice: 2900, wholesaleCost: 2465 },
  { id: 'IPH-12PM-HARD-GX', modelId: 'iph-12-pro-max', category: 'SCREENS', name: 'LCD IPH 12 PRO MAX HARD GX OR', stock: 0, retailPrice: 8500, wholesaleCost: 7225 },
  { id: 'IPH-13-GX-INCEL', modelId: 'iph-13', category: 'SCREENS', name: 'LCD IPH 13 GX INCEL', stock: 0, retailPrice: 2700, wholesaleCost: 2295 },
  { id: 'IPH-13-GX-OR', modelId: 'iph-13', category: 'SCREENS', name: 'LCD IPH 13 GX OR', stock: 0, retailPrice: 7300, wholesaleCost: 6200 },
  { id: 'IPH-13P-GX-OR', modelId: 'iph-13-pro', category: 'SCREENS', name: 'LCD IPH 13 PRO GX OR', stock: 0, retailPrice: 8300, wholesaleCost: 7055 },
  { id: 'IPH-13P-IFIX', modelId: 'iph-13-pro', category: 'SCREENS', name: 'LCD IPH 13 PRO IFIX', stock: 0, retailPrice: 8000, wholesaleCost: 6800 },
  { id: 'IPH-13PM-STD', modelId: 'iph-13-pro-max', category: 'SCREENS', name: 'LCD IPH 13 PRO MAX', stock: 0, retailPrice: 3850, wholesaleCost: 3270 },
  { id: 'IPH-13PM-GX-INCEL', modelId: 'iph-13-pro-max', category: 'SCREENS', name: 'LCD IPH 13 PRO MAX GX INCEL', stock: 0, retailPrice: 3800, wholesaleCost: 3230 },
  { id: 'IPH-13PM-GX-OR', modelId: 'iph-13-pro-max', category: 'SCREENS', name: 'LCD IPH 13 PRO MAX GX OR', stock: 0, retailPrice: 9000, wholesaleCost: 7650 },
  { id: 'IPH-13PM-IFIX', modelId: 'iph-13-pro-max', category: 'SCREENS', name: 'LCD IPH 13 PRO MAX IFIX', stock: 0, retailPrice: 5700, wholesaleCost: 4845 },
  { id: 'IPH-13PM-OLED-IFIX', modelId: 'iph-13-pro-max', category: 'SCREENS', name: 'LCD IPH 13 PRO MAX OLED IFIX', stock: 0, retailPrice: 9000, wholesaleCost: 7650 },
  { id: 'IPH-14-GX-OR', modelId: 'iph-14', category: 'SCREENS', name: 'LCD IPH 14 GX OR', stock: 0, retailPrice: 7200, wholesaleCost: 6120 },
  { id: 'IPH-14-IFIX', modelId: 'iph-14', category: 'SCREENS', name: 'LCD IPH 14 IFIX', stock: 0, retailPrice: 5500, wholesaleCost: 4675 },
  { id: 'IPH-14P-GX-INCEL', modelId: 'iph-14-pro', category: 'SCREENS', name: 'LCD IPH 14 PRO GX INCEL', stock: 0, retailPrice: 3900, wholesaleCost: 3315 },
  { id: 'IPH-14PM-STD', modelId: 'iph-14-pro-max', category: 'SCREENS', name: 'LCD IPH 14 PRO MAX', stock: 0, retailPrice: 3900, wholesaleCost: 3315 },
  { id: 'IPH-14PM-GX-INCEL', modelId: 'iph-14-pro-max', category: 'SCREENS', name: 'LCD IPH 14 PRO MAX GX INCEL', stock: 0, retailPrice: 4200, wholesaleCost: 3570 },
  { id: 'IPH-14PM-GX-OR', modelId: 'iph-14-pro-max', category: 'SCREENS', name: 'LCD IPH 14 PRO MAX GX OR', stock: 0, retailPrice: 12000, wholesaleCost: 10200 },
  { id: 'IPH-14PM-IFIX', modelId: 'iph-14-pro-max', category: 'SCREENS', name: 'LCD IPH 14 PRO MAX IFIX', stock: 0, retailPrice: 8300, wholesaleCost: 7055 },
  { id: 'IPH-14P-PS', modelId: 'iph-14-pro', category: 'SCREENS', name: 'LCD IPH 14 PRO PS', stock: 0, retailPrice: 41000, wholesaleCost: 35000, compatibilityNote: 'Pack Service Original' },
  { id: 'IPH-15-GX-OR', modelId: 'iph-15', category: 'SCREENS', name: 'LCD IPH 15 GX OR', stock: 0, retailPrice: 13800, wholesaleCost: 11730 },
  { id: 'IPH-15P-GX-OR', modelId: 'iph-15-pro', category: 'SCREENS', name: 'LCD IPH 15 PRO GX OR', stock: 0, retailPrice: 13900, wholesaleCost: 11815 },
  { id: 'IPH-15PM-STD', modelId: 'iph-15-pro-max', category: 'SCREENS', name: 'LCD IPH 15 PRO MAX', stock: 0, retailPrice: 4100, wholesaleCost: 3485 },
  { id: 'IPH-15PM-GX-INCEL', modelId: 'iph-15-pro-max', category: 'SCREENS', name: 'LCD IPH 15 PRO MAX GX INCEL', stock: 0, retailPrice: 4200, wholesaleCost: 3570 },
  { id: 'IPH-15PM-GX-OR', modelId: 'iph-15-pro-max', category: 'SCREENS', name: 'LCD IPH 15 PRO MAX GX OR', stock: 0, retailPrice: 11000, wholesaleCost: 9350 },
  { id: 'IPH-15PM-IFIX', modelId: 'iph-15-pro-max', category: 'SCREENS', name: 'LCD IPH 15 PRO MAX IFIX', stock: 0, retailPrice: 8700, wholesaleCost: 7395 },
  { id: 'IPH-15PM-IFIX-OLED', modelId: 'iph-15-pro-max', category: 'SCREENS', name: 'LCD IPH 15 PRO MAX IFIX OLED', stock: 0, retailPrice: 10700, wholesaleCost: 9095 },
  { id: 'IPH-16-GX-OR', modelId: 'iph-16', category: 'SCREENS', name: 'LCD IPH 16 GX OR', stock: 0, retailPrice: 13000, wholesaleCost: 11050 },
  { id: 'IPH-16PM-GX-IFIX-OLED', modelId: 'iph-16-pro-max', category: 'SCREENS', name: 'LCD IPH 16 PRO MAX GX IFIX HARD OLED', stock: 0, retailPrice: 14500, wholesaleCost: 12325 },
  { id: 'IPH-16PM-GX-INCEL', modelId: 'iph-16-pro-max', category: 'SCREENS', name: 'LCD IPH 16 PRO MAX GX INCEL', stock: 0, retailPrice: 8300, wholesaleCost: 7055 },
  { id: 'IPH-16PM-IFIX', modelId: 'iph-16-pro-max', category: 'SCREENS', name: 'LCD IPH 16 PRO MAX IFIX', stock: 0, retailPrice: 10500, wholesaleCost: 8925 },
  { id: 'IPH-17-GX-OR', modelId: 'iph-17', category: 'SCREENS', name: 'LCD IPH 17 GX OR', stock: 0, retailPrice: 16500, wholesaleCost: 14000 },
  { id: 'IPH-17P-GX-OR', modelId: 'iph-17-pro', category: 'SCREENS', name: 'LCD IPH 17 PRO GX OR', stock: 0, retailPrice: 16500, wholesaleCost: 14000 },
  { id: 'IPH-17PM-GX-OR', modelId: 'iph-17-pro-max', category: 'SCREENS', name: 'LCD IPH 17 PRO MAX GX OR', stock: 0, retailPrice: 16500, wholesaleCost: 14000 },
  { id: 'IPH-17PM-IFIX', modelId: 'iph-17-pro-max', category: 'SCREENS', name: 'LCD IPH 17 PRO MAX IFIX', stock: 0, retailPrice: 15000, wholesaleCost: 12750 },
  { id: 'IPH-6G-B-IFIX', modelId: 'iph-6', category: 'SCREENS', name: 'LCD IPH 6G B IFIX', stock: 0, retailPrice: 1500, wholesaleCost: 1200 },
  { id: 'IPH-6G-B-OR-IFIX', modelId: 'iph-6', category: 'SCREENS', name: 'LCD IPH 6G B OR IFIX', stock: 0, retailPrice: 1600, wholesaleCost: 1280 },
  { id: 'IPH-6G-W-IFIX', modelId: 'iph-6', category: 'SCREENS', name: 'LCD IPH 6G W IFIX', stock: 0, retailPrice: 1500, wholesaleCost: 1200 },
  { id: 'IPH-6G-W-OR-IFIX', modelId: 'iph-6', category: 'SCREENS', name: 'LCD IPH 6G W OR IFIX', stock: 0, retailPrice: 1700, wholesaleCost: 1360 },
  { id: 'IPH-6G-RECUP', modelId: 'iph-6', category: 'SCREENS', name: 'LCD IPH 6G WHITE RECUP', stock: 0, retailPrice: 1500, wholesaleCost: 1200 },
  { id: 'IPH-6S-B-IFIX', modelId: 'iph-6', category: 'SCREENS', name: 'LCD IPH 6S B IFIX', stock: 0, retailPrice: 1500, wholesaleCost: 1200 },
  { id: 'IPH-6S-W-IFIX', modelId: 'iph-6', category: 'SCREENS', name: 'LCD IPH 6S W IFIX', stock: 0, retailPrice: 1600, wholesaleCost: 1280 },
  { id: 'IPH-6SP-B-IFIX', modelId: 'iph-6-plus', category: 'SCREENS', name: 'LCD IPH 6S+ B IFIX', stock: 0, retailPrice: 1400, wholesaleCost: 1100 },
  { id: 'IPH-6SP-W-IFIX', modelId: 'iph-6-plus', category: 'SCREENS', name: 'LCD IPH 6S + W IFIX', stock: 0, retailPrice: 1400, wholesaleCost: 1100 },
  { id: 'IPH-7-B-IFIX', modelId: 'iph-7', category: 'SCREENS', name: 'LCD IPH 7G B IFIX', stock: 0, retailPrice: 1750, wholesaleCost: 1400 },
  { id: 'IPH-7-W-IFIX', modelId: 'iph-7', category: 'SCREENS', name: 'LCD IPH 7G W IFIX', stock: 0, retailPrice: 1650, wholesaleCost: 1320 },
  { id: 'IPH-7P-B-IFIX', modelId: 'iph-7-plus', category: 'SCREENS', name: 'LCD IPH 7G+ B IFIX', stock: 0, retailPrice: 2000, wholesaleCost: 1600 },
  { id: 'IPH-7P-W-IFIX', modelId: 'iph-7-plus', category: 'SCREENS', name: 'LCD IPH 7G+ W IFIX', stock: 0, retailPrice: 2200, wholesaleCost: 1760 },
  { id: 'IPH-8-B-IFIX', modelId: 'iph-8', category: 'SCREENS', name: 'LCD IPH 8G B IFIX', stock: 0, retailPrice: 2300, wholesaleCost: 1840 },
  { id: 'IPH-8-W-IFIX', modelId: 'iph-8', category: 'SCREENS', name: 'LCD IPH 8G W IFIX', stock: 0, retailPrice: 2300, wholesaleCost: 1840 },
  { id: 'IPH-X-STD', modelId: 'iph-x', category: 'SCREENS', name: 'LCD IPH X', stock: 0, retailPrice: 2150, wholesaleCost: 1720 },
  { id: 'IPH-X-FOG-IFIX', modelId: 'iph-x', category: 'SCREENS', name: 'LCD IPH X FOG IFIX', stock: 0, retailPrice: 6200, wholesaleCost: 5270 },
  { id: 'IPH-X-IFIX-OLED', modelId: 'iph-x', category: 'SCREENS', name: 'LCD IPH X IFIX OLED', stock: 0, retailPrice: 4550, wholesaleCost: 3860 },
  { id: 'IPH-XR-STD', modelId: 'iph-xr', category: 'SCREENS', name: 'LCD IPH XR', stock: 0, retailPrice: 2200, wholesaleCost: 1760 },
  { id: 'IPH-XR-IFIX', modelId: 'iph-xr', category: 'SCREENS', name: 'LCD IPH XR IFIX', stock: 0, retailPrice: 3800, wholesaleCost: 3230 },
  { id: 'IPH-XS-STD', modelId: 'iph-xs', category: 'SCREENS', name: 'LCD IPH XS', stock: 0, retailPrice: 2150, wholesaleCost: 1720 },
  { id: 'IPH-XS-OLED-IFIX', modelId: 'iph-xs', category: 'SCREENS', name: 'LCD IPH XS IFIX OLED', stock: 0, retailPrice: 4550, wholesaleCost: 3860 },
  { id: 'IPH-XSM-STD', modelId: 'iph-xs-max', category: 'SCREENS', name: 'LCD IPH XS MAX', stock: 0, retailPrice: 2500, wholesaleCost: 2000 },
  { id: 'IPH-XSM-IFIX', modelId: 'iph-xs-max', category: 'SCREENS', name: 'LCD IPH XS MAX IFIX', stock: 0, retailPrice: 3900, wholesaleCost: 3315 },
  { id: 'IPH-XSM-OLED-IFIX', modelId: 'iph-xs-max', category: 'SCREENS', name: 'LCD IPH XS MAX OLED IFIX', stock: 0, retailPrice: 6200, wholesaleCost: 5270 },

  // --- SAMSUNG ---
  { id: 'SAM-M51-OLED', modelId: 'sam-m-series', category: 'SCREENS', name: 'LCD SAM M51 OLED IFIX BIG', stock: 0, retailPrice: 5700, wholesaleCost: 4845 },
  { id: 'SAM-A013-PS', modelId: 'sam-a01', category: 'SCREENS', name: 'LCD SAM A013 PS', stock: 0, retailPrice: 1650, wholesaleCost: 1320 },
  { id: 'SAM-A015-IFIX', modelId: 'sam-a01', category: 'SCREENS', name: 'LCD SAM A015 F IFIX', stock: 0, retailPrice: 1550, wholesaleCost: 1240 },
  { id: 'SAM-A02S-A03S-BIG', modelId: 'sam-a02s-a03s', category: 'SCREENS', name: 'LCD SAM A02S / A03S BIG', stock: 0, retailPrice: 1700, wholesaleCost: 1360, compatibilityNote: 'Fits A02S, A03S' },
  { id: 'SAM-A03-CORE-PS', modelId: 'sam-a03-core', category: 'SCREENS', name: 'LCD SAM A03 CORE PS', stock: 0, retailPrice: 1900, wholesaleCost: 1520 },
  { id: 'SAM-A032-WF-PS', modelId: 'sam-a03-core', category: 'SCREENS', name: 'LCD SAM A032 A03 CORE WF PS', stock: 0, retailPrice: 2500, wholesaleCost: 2000, compatibilityNote: 'With Frame' },
  { id: 'SAM-A037-WF-PS', modelId: 'sam-a02s-a03s', category: 'SCREENS', name: 'LCD SAM A037 A03S WF PS', stock: 0, retailPrice: 2450, wholesaleCost: 1960, compatibilityNote: 'With Frame' },
  { id: 'SAM-A04-PS', modelId: 'sam-a04', category: 'SCREENS', name: 'LCD SAM A04 PS', stock: 0, retailPrice: 1900, wholesaleCost: 1520 },
  { id: 'SAM-A045-WF-PS', modelId: 'sam-a04', category: 'SCREENS', name: 'LCD SAM A045 A04 WF PS', stock: 0, retailPrice: 2500, wholesaleCost: 2000 },
  { id: 'SAM-A047-WF-PS', modelId: 'sam-a04', category: 'SCREENS', name: 'LCD SAM A047 A04S WF PS', stock: 0, retailPrice: 2500, wholesaleCost: 2000 },
  { id: 'SAM-A04E-PS', modelId: 'sam-a04', category: 'SCREENS', name: 'LCD SAM A04E PS', stock: 0, retailPrice: 1750, wholesaleCost: 1400 },
  { id: 'SAM-A055-PS', modelId: 'sam-a05', category: 'SCREENS', name: 'LCD SAM A055 A05 PS', stock: 0, retailPrice: 1800, wholesaleCost: 1440 },
  { id: 'SAM-A055-WF-PS', modelId: 'sam-a05', category: 'SCREENS', name: 'LCD SAM A055 A05 WF PS', stock: 0, retailPrice: 2350, wholesaleCost: 1880 },
  { id: 'SAM-A057-WF-PS', modelId: 'sam-a05', category: 'SCREENS', name: 'LCD SAM A057 A05S WF PS', stock: 0, retailPrice: 2650, wholesaleCost: 2120 },
  { id: 'SAM-A05S-PS', modelId: 'sam-a05', category: 'SCREENS', name: 'LCD SAM A05S PS', stock: 0, retailPrice: 1950, wholesaleCost: 1560 },
  { id: 'SAM-A06-4G-PS', modelId: 'sam-a06', category: 'SCREENS', name: 'LCD SAM A06 4G PS', stock: 0, retailPrice: 1750, wholesaleCost: 1400 },
  { id: 'SAM-A06-5G-PS', modelId: 'sam-a06', category: 'SCREENS', name: 'LCD SAM A06 5G PS', stock: 0, retailPrice: 1850, wholesaleCost: 1480 },
  { id: 'SAM-A06-WF-4G-PS', modelId: 'sam-a06', category: 'SCREENS', name: 'LCD SAM A06 WF 4G PS', stock: 0, retailPrice: 2500, wholesaleCost: 2000 },
  { id: 'SAM-A06-WF-5G-PS', modelId: 'sam-a06', category: 'SCREENS', name: 'LCD SAM A06 WF 5G PS', stock: 0, retailPrice: 2700, wholesaleCost: 2160 },
  { id: 'SAM-A07-4G-PS', modelId: 'sam-a07', category: 'SCREENS', name: 'LCD SAM A07 4G A075 PS', stock: 0, retailPrice: 1900, wholesaleCost: 1520 },
  { id: 'SAM-A07-4G-WF-PS', modelId: 'sam-a07', category: 'SCREENS', name: 'LCD SAM A07 4G WF PS', stock: 0, retailPrice: 2750, wholesaleCost: 2200 },
  { id: 'SAM-A10-PS', modelId: 'sam-a10-a10s', category: 'SCREENS', name: 'LCD SAM A10 PS', stock: 0, retailPrice: 1550, wholesaleCost: 1240 },
  { id: 'SAM-A10S-PS', modelId: 'sam-a10-a10s', category: 'SCREENS', name: 'LCD SAM A10S PS', stock: 0, retailPrice: 1650, wholesaleCost: 1320 },
  { id: 'SAM-A10S-WF-PS', modelId: 'sam-a10-a10s', category: 'SCREENS', name: 'LCD SAM A10S WF PS', stock: 0, retailPrice: 2200, wholesaleCost: 1760 },
  { id: 'SAM-A11-M11-PS', modelId: 'sam-a11-m11', category: 'SCREENS', name: 'LCD SAM A11 M11 PS', stock: 0, retailPrice: 1800, wholesaleCost: 1440, compatibilityNote: 'Fits A11 and M11' },
  { id: 'SAM-A11-WF-PS', modelId: 'sam-a11-m11', category: 'SCREENS', name: 'LCD SAM A11 WF PS', stock: 0, retailPrice: 2400, wholesaleCost: 1920 },
  { id: 'SAM-A125-PS', modelId: 'sam-a12-m12', category: 'SCREENS', name: 'LCD SAM A125 / A022 / M127 PS', stock: 0, retailPrice: 1950, wholesaleCost: 1560, compatibilityNote: 'Fits A12, A02, M12' },
  { id: 'SAM-A13-PS', modelId: 'sam-a13', category: 'SCREENS', name: 'LCD SAM A13 5.7 PS', stock: 0, retailPrice: 1950, wholesaleCost: 1560 },
  { id: 'SAM-A13-CHINA', modelId: 'sam-a13', category: 'SCREENS', name: 'LCD SAM A13 5.7 PACK CHINA', stock: 0, retailPrice: 1600, wholesaleCost: 1280 },
  { id: 'SAM-A136-5G-WF', modelId: 'sam-a13', category: 'SCREENS', name: 'LCD SAM A136 A13 5G WF PS', stock: 0, retailPrice: 2900, wholesaleCost: 2320 },
  { id: 'SAM-A14-5G-PS', modelId: 'sam-a14', category: 'SCREENS', name: 'LCD SAM A14 A145 F/B 5G PS', stock: 0, retailPrice: 1950, wholesaleCost: 1560 },
  { id: 'SAM-A14-4G-PS', modelId: 'sam-a14', category: 'SCREENS', name: 'LCD SAM A14 A145P 4G PS', stock: 0, retailPrice: 1850, wholesaleCost: 1480 },
  { id: 'SAM-A145P-WF-4G', modelId: 'sam-a14', category: 'SCREENS', name: 'LCD SAM A145P WF 4G PS', stock: 0, retailPrice: 2700, wholesaleCost: 2160 },
  { id: 'SAM-A146B-WF-5G', modelId: 'sam-a14', category: 'SCREENS', name: 'LCD SAM A146B / A145F WF 5G PS', stock: 0, retailPrice: 2700, wholesaleCost: 2160 },
  { id: 'SAM-A15-5G-BLK-PS', modelId: 'sam-a15', category: 'SCREENS', name: 'LCD SAM A15 5G BLK PS', stock: 0, retailPrice: 9300, wholesaleCost: 7900, compatibilityNote: 'Pack Service Original' },
  { id: 'SAM-A15-OLED-WF-IFIX', modelId: 'sam-a15', category: 'SCREENS', name: 'LCD SAM A15 OLED WF IFIX', stock: 0, retailPrice: 5800, wholesaleCost: 4930, compatibilityNote: 'OLED With Frame' },
  { id: 'SAM-A15-WF-ASSEMBLED', modelId: 'sam-a15', category: 'SCREENS', name: 'LCD SAM A15 WF ASSEMBLED', stock: 0, retailPrice: 8500, wholesaleCost: 7225 },
  { id: 'SAM-A16-M16-PS', modelId: 'sam-a16', category: 'SCREENS', name: 'LCD SAM A16 / M16 PS ONLY', stock: 0, retailPrice: 9300, wholesaleCost: 7900, compatibilityNote: 'Fits A16 and M16' },
  { id: 'SAM-A16-4G-OLED-IFIX', modelId: 'sam-a16', category: 'SCREENS', name: 'LCD SAM A16 4G WF OLED BIG IFIX', stock: 0, retailPrice: 6500, wholesaleCost: 5525 },
  { id: 'SAM-A16-5G-OLED-IFIX', modelId: 'sam-a16', category: 'SCREENS', name: 'LCD SAM A16 5G WF OLED BIG IFIX', stock: 0, retailPrice: 6300, wholesaleCost: 5355 },
  { id: 'SAM-A165-MULTI-OLED', modelId: 'sam-a16', category: 'SCREENS', name: 'LCD SAM A165 / A166 / A17 5G / A26 5G OLED BIG IFIX', stock: 0, retailPrice: 5900, wholesaleCost: 5015, compatibilityNote: 'Universal fit: A16 4G/5G, A17 5G, A26 5G' },
  { id: 'SAM-A17-5G-WF-PS', modelId: 'sam-a17', category: 'SCREENS', name: 'LCD SAM A17 5G /4G WF PS', stock: 0, retailPrice: 10800, wholesaleCost: 9180 },
  { id: 'SAM-A20-INCELL-IFIX', modelId: 'sam-a20-a20s', category: 'SCREENS', name: 'LCD SAM A20 INCELL ONLY IFIX', stock: 0, retailPrice: 1750, wholesaleCost: 1400 },
  { id: 'SAM-A20-OLED-IFIX', modelId: 'sam-a20-a20s', category: 'SCREENS', name: 'LCD SAM A20 OLED IFIX SUPER AMOLED', stock: 0, retailPrice: 4300, wholesaleCost: 3655 },
  { id: 'SAM-A20S-PS', modelId: 'sam-a20-a20s', category: 'SCREENS', name: 'LCD SAM A20S PS', stock: 0, retailPrice: 1750, wholesaleCost: 1400 },
  { id: 'SAM-A21S-PS', modelId: 'sam-a21s', category: 'SCREENS', name: 'LCD SAM A21S PS', stock: 0, retailPrice: 2100, wholesaleCost: 1680 },
  { id: 'SAM-A22-M22-PS', modelId: 'sam-a22', category: 'SCREENS', name: 'LCD SAM A22 / M22 / F22 4G ONLY PS', stock: 0, retailPrice: 5150, wholesaleCost: 4375, compatibilityNote: 'Fits A22 4G, M22, F22' },
  { id: 'SAM-A22-OLED-IFIX', modelId: 'sam-a22', category: 'SCREENS', name: 'LCD SAM A22 WF OLED IFIX', stock: 0, retailPrice: 4300, wholesaleCost: 3655 },
  { id: 'SAM-A23-4G-WF-PS', modelId: 'sam-a23', category: 'SCREENS', name: 'LCD SAM A235 A23 4G WF PS', stock: 0, retailPrice: 2800, wholesaleCost: 2240 },
  { id: 'SAM-A23-5G-WF-PS', modelId: 'sam-a23', category: 'SCREENS', name: 'LCD SAM A236 A23 5G WF PS', stock: 0, retailPrice: 2800, wholesaleCost: 2240 },
  { id: 'SAM-A24-OLED-BIG-IFIX', modelId: 'sam-a24', category: 'SCREENS', name: 'LCD SAM A24 / M34 / A25 OLED BIG ONLY IFIX', stock: 0, retailPrice: 5400, wholesaleCost: 4590, compatibilityNote: 'Cross-compatible: A24, M34, A25' },
  { id: 'SAM-A24-WF-OLED-BIG', modelId: 'sam-a24', category: 'SCREENS', name: 'LCD SAM A24 OLED BIG WF IFIX', stock: 0, retailPrice: 5500, wholesaleCost: 4675 },
  { id: 'SAM-A25-WF-PS', modelId: 'sam-a25', category: 'SCREENS', name: 'LCD SAM A25 WF PS', stock: 0, retailPrice: 12500, wholesaleCost: 10625 },
  { id: 'SAM-A25-OLED-BIG-WF', modelId: 'sam-a25', category: 'SCREENS', name: 'LCD SAM A25 OLED BIG WF IFIX', stock: 0, retailPrice: 5500, wholesaleCost: 4675 },
  { id: 'SAM-A26-5G-OLED-IFIX', modelId: 'sam-a26', category: 'SCREENS', name: 'LCD SAM A26 5G OLED BIG WF IFIX', stock: 0, retailPrice: 6500, wholesaleCost: 5525 },
  { id: 'SAM-A30-A50-INCELL', modelId: 'sam-a30-a50', category: 'SCREENS', name: 'LCD SAM A30 / A50 INCELL WF IFIX', stock: 0, retailPrice: 2200, wholesaleCost: 1760, compatibilityNote: 'Fits A30 & A50' },
  { id: 'SAM-A30S-OLED-IFIX', modelId: 'sam-a30-a50', category: 'SCREENS', name: 'LCD SAM A30S OLED IFIX SUPER AMOLED', stock: 0, retailPrice: 4050, wholesaleCost: 3440 },
  { id: 'SAM-A31-OLED-IFIX', modelId: 'sam-a31', category: 'SCREENS', name: 'LCD SAM A31 OLED WF IFIX', stock: 0, retailPrice: 4350, wholesaleCost: 3700 },
  { id: 'SAM-A32-4G-OLED-IFIX', modelId: 'sam-a32', category: 'SCREENS', name: 'LCD SAM A32 4G OLED WF IFIX', stock: 0, retailPrice: 4600, wholesaleCost: 3910 },
  { id: 'SAM-A33-PS-GOLD', modelId: 'sam-a33', category: 'SCREENS', name: 'LCD SAM A33 5G A336 PS GOLD', stock: 0, retailPrice: 13200, wholesaleCost: 11220 },
  { id: 'SAM-A34-F54-OLED', modelId: 'sam-a34', category: 'SCREENS', name: 'LCD SAM A34 / F54 OLED', stock: 0, retailPrice: 4400, wholesaleCost: 3740, compatibilityNote: 'Fits A34 & F54' },
  { id: 'SAM-A34-5G-GREEN-PS', modelId: 'sam-a34', category: 'SCREENS', name: 'LCD SAM A34 5G GREEN PS', stock: 0, retailPrice: 15500, wholesaleCost: 13175 },
  { id: 'SAM-A35-5G-OLED-WF', modelId: 'sam-a35', category: 'SCREENS', name: 'LCD SAM A35 5G OLED WF', stock: 0, retailPrice: 4900, wholesaleCost: 4165 },
  { id: 'SAM-A36-5G-OLED', modelId: 'sam-a36', category: 'SCREENS', name: 'LCD SAM A36 5G WF OLED', stock: 0, retailPrice: 4900, wholesaleCost: 4165 },
  { id: 'SAM-A51-OLED-IFIX', modelId: 'sam-a51', category: 'SCREENS', name: 'LCD SAM A51 WF OLED IFIX', stock: 0, retailPrice: 4700, wholesaleCost: 3995 },
  { id: 'SAM-A52-OLED-IFIX', modelId: 'sam-a52', category: 'SCREENS', name: 'LCD SAM A52 BIG WF BLACK OLED IFIX', stock: 0, retailPrice: 5400, wholesaleCost: 4590 },
  { id: 'SAM-A53-5G-PS', modelId: 'sam-a53', category: 'SCREENS', name: 'LCD SAM A53 5G WHITE PS', stock: 0, retailPrice: 16500, wholesaleCost: 14025 },
  { id: 'SAM-A54-5G-OLED-IFIX', modelId: 'sam-a54', category: 'SCREENS', name: 'LCD SAM A54 OLED WF IFIX', stock: 0, retailPrice: 6100, wholesaleCost: 5185 },
  { id: 'SAM-A54-5G-BLK-PS', modelId: 'sam-a54', category: 'SCREENS', name: 'LCD SAM A54 5G BLK PS', stock: 0, retailPrice: 16700, wholesaleCost: 14195 },
  { id: 'SAM-A55-5G-PS', modelId: 'sam-a55', category: 'SCREENS', name: 'LCD SAM A55 5G BLEU PS', stock: 0, retailPrice: 15500, wholesaleCost: 13175 },
  { id: 'SAM-A55-INCELL-IFIX', modelId: 'sam-a55', category: 'SCREENS', name: 'LCD SAM A55 5G WF INCEL IFIX', stock: 0, retailPrice: 3200, wholesaleCost: 2720 },
  { id: 'SAM-A56-5G-OLED', modelId: 'sam-a56', category: 'SCREENS', name: 'LCD SAM A56 5G WF OLED', stock: 0, retailPrice: 5500, wholesaleCost: 4675 },
  { id: 'SAM-A70-INCELL', modelId: 'sam-a70-a71-a72-a73', category: 'SCREENS', name: 'LCD SAM A70 INCELL WF IFIX', stock: 0, retailPrice: 2250, wholesaleCost: 1800 },
  { id: 'SAM-A71-OLED', modelId: 'sam-a70-a71-a72-a73', category: 'SCREENS', name: 'LCD SAM A71 WF OLED', stock: 0, retailPrice: 4500, wholesaleCost: 3825 },
  { id: 'SAM-A72-OLED', modelId: 'sam-a70-a71-a72-a73', category: 'SCREENS', name: 'LCD SAM A72 OLED WF', stock: 0, retailPrice: 4900, wholesaleCost: 4165 },
  { id: 'SAM-A73-OLED', modelId: 'sam-a70-a71-a72-a73', category: 'SCREENS', name: 'LCD SAM A73 WF OLED', stock: 0, retailPrice: 4900, wholesaleCost: 4165 },
  { id: 'SAM-S20FE-OLED', modelId: 'sam-s20', category: 'SCREENS', name: 'LCD SAM S20 FE OLED WF IFIX', stock: 0, retailPrice: 5500, wholesaleCost: 4675 },
  { id: 'SAM-S20U-OLED', modelId: 'sam-s20', category: 'SCREENS', name: 'LCD SAM S20 ULTRA OLED WF IFIX', stock: 0, retailPrice: 13500, wholesaleCost: 11475 },
  { id: 'SAM-S21-PS', modelId: 'sam-s21', category: 'SCREENS', name: 'LCD SAM S21 5G GRIS PS', stock: 0, retailPrice: 28500, wholesaleCost: 24225 },
  { id: 'SAM-S21U-OLED', modelId: 'sam-s21', category: 'SCREENS', name: 'LCD SAM S21 ULTRA OLED WF IFIX', stock: 0, retailPrice: 14500, wholesaleCost: 12325 },
  { id: 'SAM-S22U-GREEN-PS', modelId: 'sam-s22', category: 'SCREENS', name: 'LCD SAM S22 ULTRA GREEN PS', stock: 0, retailPrice: 54000, wholesaleCost: 46000 },
  { id: 'SAM-S23U-PS', modelId: 'sam-s23', category: 'SCREENS', name: 'LCD SAM S23 ULTRA BLK PS', stock: 0, retailPrice: 57000, wholesaleCost: 48500 },
  { id: 'SAM-S24U-WF-PS', modelId: 'sam-s24', category: 'SCREENS', name: 'LCD SAM S24 ULTRA BLK WF PS', stock: 0, retailPrice: 52000, wholesaleCost: 44200 },
  { id: 'SAM-S25U-OLED', modelId: 'sam-s25', category: 'SCREENS', name: 'LCD SAM S25 ULTRA OLED WF IFIX', stock: 0, retailPrice: 18700, wholesaleCost: 15895 },
  { id: 'SAM-Z-FLIP6-PS', modelId: 'sam-z-flip6', category: 'SCREENS', name: 'LCD SAM Z FLIP 6 BLK WF PS', stock: 0, retailPrice: 65000, wholesaleCost: 55000 },

  // --- INFINIX & TECNO & ITEL ---
  { id: 'INF-HOT9-PLAY', modelId: 'inf-hot-series', category: 'SCREENS', name: 'LCD IINFINX HOT 9 PLAY IFIX', stock: 0, retailPrice: 1600, wholesaleCost: 1280 },
  { id: 'INF-HOT10-PLAY', modelId: 'inf-hot-series', category: 'SCREENS', name: 'LCD INFINIX HOT 10 PLAY / P37 PRO / HOT 11 PLAY IFIX', stock: 0, retailPrice: 1650, wholesaleCost: 1320, compatibilityNote: 'Cross-compatible: Hot 10 Play, P37 Pro, Hot 11 Play' },
  { id: 'INF-HOT50-PRO-PLUS', modelId: 'inf-hot-series', category: 'SCREENS', name: 'LCD INFINIX HOT 50 PRO PLUS / NOTE 40 PRO OLED IFIX', stock: 0, retailPrice: 6500, wholesaleCost: 5525, compatibilityNote: 'Fits Hot 50 Pro+ & Note 40 Pro' },
  { id: 'INF-SMART8', modelId: 'inf-smart-series', category: 'SCREENS', name: 'LCD INFINIX SMART 8 / SPARK GO 2024 / POP 8 / HOT 40I', stock: 0, retailPrice: 1600, wholesaleCost: 1280, compatibilityNote: 'Universal fit: Smart 8, Spark Go 2024, Spark 20, Pop 8, Hot 40i' },
  { id: 'INF-SMART9', modelId: 'inf-smart-series', category: 'SCREENS', name: 'LCD INFINIX SMART 9 / A80 ITEL / HOT 50 5G / SPARK 30C / POP 9', stock: 0, retailPrice: 1650, wholesaleCost: 1320, compatibilityNote: 'Universal fit: Smart 9, A80 Itel, Hot 50 5G, Spark 30C, Pop 9' },
  { id: 'ITEL-S23-SMART7', modelId: 'itel-a-series', category: 'SCREENS', name: 'LCD ITEL S23 / HOT 30I / SMART 7 / SMART 7 HD IFIX', stock: 0, retailPrice: 1650, wholesaleCost: 1320, compatibilityNote: 'Fits S23, Hot 30i, Smart 7, Smart 7 HD' },
  { id: 'TECNO-CAMON18-SPARK8', modelId: 'tecno-camon-spark', category: 'SCREENS', name: 'LCD TECHNO CAMON 18 PRO / SPARK 8 PRO / HOT 11S IFIX', stock: 0, retailPrice: 2100, wholesaleCost: 1680, compatibilityNote: 'Fits Camon 18/17 Pro, Spark 8 Pro, Hot 11S/20S' },

  // --- OPPO & REALME ---
  { id: 'OPPO-A15-C11', modelId: 'oppo-a-series', category: 'SCREENS', name: 'LCD OPPO A15 / C11 / C12 OR IFIX', stock: 0, retailPrice: 1480, wholesaleCost: 1180, compatibilityNote: 'Fits Oppo A15, Realme C11, C12' },
  { id: 'OPPO-A16-A54S', modelId: 'oppo-a-series', category: 'SCREENS', name: 'LCD OPPO A16 / A16S / A54S / C25S OR IFIX', stock: 0, retailPrice: 1530, wholesaleCost: 1220, compatibilityNote: 'Fits Oppo A16, A54S, Realme C25S' },
  { id: 'OPPO-A53-A54', modelId: 'oppo-a-series', category: 'SCREENS', name: 'LCD OPPO A53 / A54 4G / REALME 7I / C17 OR IFIX', stock: 0, retailPrice: 1700, wholesaleCost: 1360, compatibilityNote: 'Fits Oppo A53, A54 4G, Realme 7i, C17' },
  { id: 'OPPO-RENO-12F-OLED', modelId: 'oppo-reno-series', category: 'SCREENS', name: 'LCD OPPO RENO 12F / 13F / REALME 12 / 13 OLED IFIX', stock: 0, retailPrice: 5450, wholesaleCost: 4630, compatibilityNote: 'Fits Reno 12F/13F, Realme 12/13' },
  { id: 'REALME-C61-C63', modelId: 'realme-c-series', category: 'SCREENS', name: 'LCD REALME C61 / C63 / NOTE 60 IFIX', stock: 0, retailPrice: 1600, wholesaleCost: 1280, compatibilityNote: 'Fits Realme C61, C63, Note 60' },
  { id: 'REALME-NOTE50-C53', modelId: 'realme-c-series', category: 'SCREENS', name: 'LCD REALME NOTE 50 C53 C51 OR IFIX', stock: 0, retailPrice: 1550, wholesaleCost: 1240, compatibilityNote: 'Fits Realme Note 50, C53, C51' },

  // --- XIAOMI & REDMI & POCO ---
  { id: 'REDMI-9A-9C', modelId: 'xiaomi-redmi-numbered', category: 'SCREENS', name: 'LCD REDMI 9A / 9C OR', stock: 0, retailPrice: 1450, wholesaleCost: 1160, compatibilityNote: 'Fits 9A & 9C' },
  { id: 'REDMI-12-13-M6', modelId: 'xiaomi-redmi-numbered', category: 'SCREENS', name: 'LCD REDMI 12 / REDMI 13 / POCO M6 PRO 5G / NOTE 12R', stock: 0, retailPrice: 1950, wholesaleCost: 1560, compatibilityNote: 'Fits Redmi 12/13, Poco M6 Pro 5G, Note 12R' },
  { id: 'REDMI-13C-C67', modelId: 'xiaomi-redmi-numbered', category: 'SCREENS', name: 'LCD REDMI 13C OR / C67 POCO IFIX', stock: 0, retailPrice: 1550, wholesaleCost: 1240, compatibilityNote: 'Fits Redmi 13C & Poco C67' },
  { id: 'REDMI-14C-POCO-C71', modelId: 'xiaomi-redmi-numbered', category: 'SCREENS', name: 'LCD REDMI 14C / POCO C71 / JIVO V20 OR IFIX', stock: 0, retailPrice: 1550, wholesaleCost: 1240 },
  { id: 'REDMI-NOTE10-OLED', modelId: 'xiaomi-redmi-note', category: 'SCREENS', name: 'LCD REDMI NOTE 10 4G / NOTE 10S IFIX OLED', stock: 0, retailPrice: 4650, wholesaleCost: 3950, compatibilityNote: 'Fits Note 10 4G & Note 10S' },
  { id: 'REDMI-NOTE11-12-OLED', modelId: 'xiaomi-redmi-note', category: 'SCREENS', name: 'LCD REDMI NOTE 10 PRO OLED / NOTE 11 PRO / NOTE 12 PRO / X4 PRO 5G IFIX', stock: 0, retailPrice: 5500, wholesaleCost: 4675, compatibilityNote: 'Universal fit: Note 10 Pro, 11 Pro, 12 Pro, Poco X4 Pro' },
  { id: 'REDMI-NOTE13-14-OLED', modelId: 'xiaomi-redmi-note', category: 'SCREENS', name: 'LCD REDMI NOTE 13 4G / NOTE 14 4G OLED', stock: 0, retailPrice: 5400, wholesaleCost: 4590, compatibilityNote: 'Fits Note 13 4G & Note 14 4G' },
  { id: 'POCO-X3-PRO', modelId: 'xiaomi-poco-series', category: 'SCREENS', name: 'LCD POCO X3 X3 PRO MI 10T LTE / NOTE 9 PRO 5G IFIX', stock: 0, retailPrice: 2000, wholesaleCost: 1600, compatibilityNote: 'Fits Poco X3/X3 Pro, Mi 10T Lite, Note 9 Pro 5G' },

  // --- ACE BUZZ & CONDOR ---
  { id: 'ACE-BUZZ-6-PRIME', modelId: 'ace-buzz-models', category: 'SCREENS', name: 'LCD ACE BUZZ 6 PRIM / 6 LITE / BLACK VIEW A85', stock: 0, retailPrice: 2250, wholesaleCost: 1800, compatibilityNote: 'Fits Buzz 6 Prime, 6 Lite, Blackview A85' },
  { id: 'CONDOR-NOVA-70', modelId: 'condor-models', category: 'SCREENS', name: 'LCD CONDOR NOVA 70 SE RUCUP', stock: 0, retailPrice: 2800, wholesaleCost: 2240 },

  // --- HUAWEI & HONOR ---
  { id: 'HUW-P30-PRO-OLED', modelId: 'huw-p-mate-series', category: 'SCREENS', name: 'LCD HUW P30 PRO BLK WF OR', stock: 0, retailPrice: 11500, wholesaleCost: 9775 },
  { id: 'HUW-PURA-70-ULTRA', modelId: 'huw-p-mate-series', category: 'SCREENS', name: 'LCD HUW PURA 70 UTRA / PURA 70 PRO OR', stock: 0, retailPrice: 48000, wholesaleCost: 40800 },
  { id: 'HONOR-X9A-INCEL', modelId: 'honor-series', category: 'SCREENS', name: 'LCD HUW X9A INCEL IFIX', stock: 0, retailPrice: 4500, wholesaleCost: 3825 },

  // --- GOOGLE PIXEL & ONEPLUS ---
  { id: 'PIXEL-7-OLED', modelId: 'google-pixel-models', category: 'SCREENS', name: 'LCD GOOGLE PIXEL 7 OLED', stock: 0, retailPrice: 11200, wholesaleCost: 9520 },
  { id: 'PIXEL-8-PRO-ORG', modelId: 'google-pixel-models', category: 'SCREENS', name: 'LCD GOOGLE PIXEL 8 PRO ORG', stock: 0, retailPrice: 34500, wholesaleCost: 29325 },
  { id: 'PIXEL-9-PRO-ORG', modelId: 'google-pixel-models', category: 'SCREENS', name: 'LCD GOOGLE PIXEL 9 PRO / 9 PRO XL ORG', stock: 0, retailPrice: 28500, wholesaleCost: 24225 },
  { id: 'ONEPLUS-NORD-ORG', modelId: 'oneplus-models', category: 'SCREENS', name: 'LCD ONE PLUS NORD ORG / REALME X50 PRO', stock: 0, retailPrice: 20500, wholesaleCost: 17425, compatibilityNote: 'Fits OnePlus Nord & Realme X50 Pro' },
];
